[".zshrc"]
    type = "file"
    url = "https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc"
    refreshPeriod = "168h"

[".config/alacritty/themes/solarized-dark.toml"]
    type = "file"
    url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/solarized_dark.toml"
    refreshPeriod = "168h"
