[".zshrc"]
    type = "file"
    url = "https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc"
    refreshPeriod = "168h"

[".config/alacritty/themes/github-dark-dimmed.toml"]
    type = "file"
    url = "https://raw.githubusercontent.com/alacritty/alacritty-theme/master/themes/github_dark_dimmed.toml"
    refreshPeriod = "168h"
