actions:
- action: file.link
  from: zshrc
  to: /home/mriehl/.zshrc

- action: file.link
  from: zshrc.local
  to: /home/mriehl/.zshrc.local

- action: file.link
  from: i3
  to: /home/mriehl/.i3

- action: file.link
  from: gitconfig
  to: /home/mriehl/.gitconfig

- action: file.link
  from: tmux.conf
  to: /home/mriehl/.tmux.conf

- action: file.link
  from: pythonrc.py
  to: /home/mriehl/.pythonrc.py

- action: file.link
  from: gpg-agent.conf
  to: /home/mriehl/.gnupg/gpg-agent.conf

- action: file.link
  from: gpg.conf
  to: /home/mriehl/.gnupg/gpg.conf

- action: file.link
  from: emacs.d
  to: /home/mriehl/.emacs.d

- action: command.run
  dir: /home/mriehl/.emacs.d
  command: git
  args:
  - clone
  - git@github.com:brocode/emacs_subconfigs.git
  - subconfigs

- action: file.copy
  from: emacs.service
  to: /home/mriehl/.config/systemd/user/emacs.service

- action: file.copy
  from: ssh-agent.service
  to: /home/mriehl/.config/systemd/user/ssh-agent.service

- action: file.link
  from: rustfmt.toml
  to: /home/mriehl/.rustfmt.toml

- action: file.link
  from: dunstrc
  to: /home/mriehl/.config/dunst/dunstrc

- action: file.link
  from: starship.toml
  to: /home/mriehl/.config/starship.toml

- action: file.link
  from: alacritty.yml
  to: /home/mriehl/.config/alacritty.yml

- action: file.link
  from: xsession
  to: /home/mriehl/.xsession

- action: file.link
  from: xsessionrc
  to: /home/mriehl/.xsessionrc

- action: file.link
  from: i3lock.sh
  to: /home/mriehl/scripts/i3lock.sh

- action: file.link
  from: key_layout
  to: /home/mriehl/scripts/key_layout
