depends:
- pkg

actions:
- action: command.run
  command: rustup
  args:
  - toolchain
  - install
  - stable

- action: command.run
  command: rustup
  args:
  - toolchain
  - install
  - nightly

- action: command.run
  command: rustup
  args:
  - component
  - add
  - rustc-dev
  - --toolchain=nightly
