depends:
- pkg
actions:
- action: command.run
  command: mkdir
  args:
  - -p
  - {{ user.home_dir }}/.dotfiles_slowpkg_installed
- action: package.install
  where: |
    path = "{{ user.home_dir }}/.dotfiles_slowpkg_installed/fira-installed"
    exists = io.exists path
    if exists
      io.print "file found"
      false
    else
      io.print "no file found"
      io.create path
      true
  provider: yay
  list:
  - nerd-fonts-fira-code
- action: package.install
  where: |
    path = "{{ user.home_dir }}/.dotfiles_slowpkg_installed/i3blocks-contrib-installed"
    exists = io.exists path
    if exists
      io.print "file found"
      false
    else
      io.print "no file found"
      io.create path
      true
  provider: yay
  list:
  - i3blocks-contrib
- action: package.install
  where: |
    path = "{{ user.home_dir }}/.dotfiles_slowpkg_installed/visual-studio-code-bin-installed"
    exists = io.exists path
    if exists
      io.print "file found"
      false
    else
      io.print "no file found"
      io.create path
      true
  provider: yay
  list:
  - visual-studio-code-bin
